// Core Imports
const express = require("express");

// Custom Imports
const upload = require("./../../file-upload");
const RESPONSE_TYPES = require("./../../response-types");

const router = express.Router();
const singleUpload = upload.single("file");

router.post("/upload-file", (req, res, next) => {
  //   if (!req.file) {
  //     // this "req.file" is automated generated by multer package, and by now, file is uploaded in system and this "file" object contains file path in "path" veriable inside it.
  //     return res.status(RESPONSE_TYPES.INVALID_INPUT.statusCode).json({
  //       message: RESPONSE_TYPES.INVALID_INPUT.message,
  //       errors: {
  //         file: "this is required.",
  //         oldFilePath:
  //           "provide old file path, this will save storage space by deleting that file",
  //       },
  //       statusCode: RESPONSE_TYPES.INVALID_INPUT.statusCode,
  //     });
  //   } else {
  //     if (req.body.oldFilePath) {
  //       UTILS.removeImage(req.body.oldFilePath);
  //     }
  singleUpload(req, res, (err) => {
    return res.status(RESPONSE_TYPES.SUCCESS.statusCode).json({
      message: RESPONSE_TYPES.SUCCESS.message,
      statusCode: RESPONSE_TYPES.SUCCESS.statusCode,
      file: {
        url: req.file.location,
      },
    });
  });
  //   }
});

module.exports = router;
